### ISSUE TITLE
Textausgabe

### ISSUE THREAD

**Issue by MG020162** [MoJoKi42/flipControl#1]
Gibt es ein Beispiel was alles über die serielle Schnittstelle gesendet werden muss um ein Text auszugeben? Die Hardware funktioniert soweit, die Dots schalten beim betätigen der Gelb und Schwarz Taster. Danke für die Hilfe.

**Comment by MoJoKi42** [comment]
[Doku.pdf](https://github.com/user-attachments/files/17298290/Doku.pdf)
[FlipControl V1.2 vorläufig.py.zip](https://github.com/user-attachments/files/17298307/FlipControl.V1.2.vorlaufig.py.zip)

Ich habe hier eine noch nicht fertige Doku inkl. zugehöriger Python Lib. Sollte aber eigentlich weitgehend funktionieren. Hoffe damit konnte ich dir helfen.
